### ISSUE TITLE
404 after installation

### ISSUE THREAD

**Issue by glewe** [adriansuter/Slim4-Skeleton#16]
HI Adrian,
installed your skeleton with Xampp on Windows using composer as documented.
When pointing my browser to the /public route I get

```
404 Not Found

The application could not run because of the following error:
Details
Type: Slim\Exception\HttpNotFoundException
Code: 404
Message: Not found.
File: D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php
Line: 93
Trace

#0 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(59): Slim\Middleware\RoutingMiddleware->performRouting(Object(Nyholm\Psr7\ServerRequest))
#1 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(Slim\Routing\RouteRunner))
#2 D:\Web\htdocs\lewe\slim41\vendor\slim\twig-view\src\TwigMiddleware.php(70): class@anonymous->handle(Object(Nyholm\Psr7\ServerRequest))
#3 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Views\TwigMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(class@anonymous))
#4 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(98): class@anonymous->handle(Object(Nyholm\Psr7\ServerRequest))
#5 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Nyholm\Psr7\ServerRequest), Object(class@anonymous))
#6 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Nyholm\Psr7\ServerRequest))
#7 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\App.php(211): Slim\MiddlewareDispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#8 D:\Web\htdocs\lewe\slim41\vendor\slim\slim\Slim\App.php(195): Slim\App->handle(Object(Nyholm\Psr7\ServerRequest))
#9 D:\Web\htdocs\lewe\slim41\public\index.php(74): Slim\App->run()
#10 {main}
```
Any ideas?

Brds,
George

**Comment by adriansuter** [comment]
Hi there

Probably it is because the routes defined in `index.php` are such that your web root is pointing to the public directory. So your request should not contain `public`.

Either you change your server configuration such that localhost is pointing to the public dir (and then request `http://localhost` or you set the base path of the app right after creating it.

**Comment by glewe** [comment]
Thanks Adrian,
that helped. Setting the base path right after app creation fixed it.
Brgds
George
